// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRgra3qdhFI-wg1r6GKGCHShuoohhKTZQ',
    appId: '1:802131498495:web:efd2a29d3ac5692e7ac3ca',
    messagingSenderId: '802131498495',
    projectId: 'my-flutter-web-a5f3f',
    authDomain: 'my-flutter-web-a5f3f.firebaseapp.com',
    storageBucket: 'my-flutter-web-a5f3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcQLDct_NJweJ4RMTHKlvji_hl11u8U4k',
    appId: '1:802131498495:android:a4bfc4d113c0c4127ac3ca',
    messagingSenderId: '802131498495',
    projectId: 'my-flutter-web-a5f3f',
    storageBucket: 'my-flutter-web-a5f3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWx89laCyPpTWesXg2qlZHR-Lt_WhfOsc',
    appId: '1:802131498495:ios:f93d8fcac0ed5d5e7ac3ca',
    messagingSenderId: '802131498495',
    projectId: 'my-flutter-web-a5f3f',
    storageBucket: 'my-flutter-web-a5f3f.appspot.com',
    iosClientId: '802131498495-ujal2am5ann42rbq27ou4o0aias93k0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.userloginWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWx89laCyPpTWesXg2qlZHR-Lt_WhfOsc',
    appId: '1:802131498495:ios:f93d8fcac0ed5d5e7ac3ca',
    messagingSenderId: '802131498495',
    projectId: 'my-flutter-web-a5f3f',
    storageBucket: 'my-flutter-web-a5f3f.appspot.com',
    iosClientId: '802131498495-ujal2am5ann42rbq27ou4o0aias93k0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.userloginWeb',
  );
}
